export const sliderItems = [
  {
    id: 1,
    image: "https://i.ibb.co/cXFnLLV/3.png",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    image: "https://i.ibb.co/DG69bQ4/2.png",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    image: "https://i.ibb.co/cXFnLLV/3.png",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    image:
      "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LADY",
    category: "Lady",
  },
  {
    id: 2,
    image: "/images/men.jpg",
    title: "MEN",
    category: "Men",
  },
  {
    id: 3,
    image:
      "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "ACCESSORIES",
    category: "",
  },
];

export const products = [
  {
    id: 1,
    name: "T/W Gabardine Asymmetry Jacket",
    image: "/images/TW Gabardine Asymmetry Jacket.webp",
    price: 576,
    color: ["Black"],
    categories: ["Outerwear", "Lady"],
    size: ["XS", "M"],
    desc: "Packaged for all season using classic wool / polyester fabric. It is created with durable fabric that is uniquely glossy and beautifully draped.",
  },
  {
    id: 2,
    name: "PLAIN STITCH x DROP STITCH CRASH KNIT",
    image: "/images/PLAIN STITCH x DROP STITCH CRASH KNIT.webp",
    price: 527,
    color: ["Black"],
    categories: ["Sweater", "Lady"],
    size: ["S"],
    desc: "This jersey knit has a lustrous, falling texture and a moist feel. You can enjoy a layered style with innerwear peeking out from the crushed part.",
  },
  {
    id: 3,
    name: "Triangle random border Drape big T",
    image: "/images/Triangle random border Drape big T.webp",
    price: 384,
    color: ["White", "Black"],
    categories: ["Shirt", "Lady", "Men"],
    size: ["M"],
    desc: "A jacquard with a smooth texture using compact yarn. At first glance it looks like patchwork, but it's all made of jacquard on a single piece of fabric, making it a flat and comfortable fabric.",
  },
  {
    id: 4,
    name: "Triangle random border Big Sleeves hoodie",
    image: "/images/Triangle random border Big Sleeves hoodie.webp",
    price: 528,
    color: ["Black", "White"],
    categories: ["Hoodie", "Lady", "Men"],
    size: ["M"],
    desc: "A jacquard with a smooth texture using compact yarn. At first glance it looks like patchwork, but it's all made of jacquard on a single piece of fabric, making it a flat and comfortable fabric.",
  },
  {
    id: 5,
    name: "40/2 Cotton Jersey Stitching Slit Crow on Lungs and Flowers Message T-shirt",
    image:
      "/images/402 Cotton Jersey Stitching Slit Crow on Lungs and Flowers Message T-shirt.webp",
    price: 125,
    color: ["Black", "White"],
    categories: ["Shirt", "Lady", "Men"],
    size: ["M"],
    desc: "The balance between the consecutive prohibited messages and the remake design on the half of the t-shirt, which looks as if it was sewn by dismantling big body t-shirts of different sizes and shifting them from the front and back center, is the ultimate. ",
  },
  {
    id: 6,
    name: "Pe / Chiffon A Drape Jacket",
    image: "/images/Pe  Chiffon A Drape Jacket.webp",
    price: 540,
    color: ["Black", "White"],
    categories: ["Outerwear", "Lady"],
    size: ["S"],
    desc: "A jacket with an impressive front body volume and slits on the cuffs. It is a design that you can enjoy the texture of the material with light comfort.",
  },
  {
    id: 7,
    name: "Pe/Chiffon A Layerd Stole Blouse",
    image: "/images/Pe Chiffon A Layerd Stole Blouse.webp",
    price: 405,
    color: ["Black", "White"],
    categories: ["Shirt", "Lady"],
    size: ["S"],
    desc: "Polyester chiffon with a soft surface, elegant sheerness, and drape. A delicate fabric that gives a feminine impression.",
  },
  {
    id: 8,
    name: "Pe / Chiffon A Front Drape Sleeveless Dress",
    image: "/images/Pe Chiffon A Front Drape Sleeveless Dress.webp",
    price: 513,
    color: ["Black", "White"],
    categories: ["Dress", "Lady"],
    size: ["S"],
    desc: "A dress with a sense of volume and drape on the front characterized. It is a sleeveless and clean impression like spring and summer.",
  },
  {
    id: 9,
    name: "Vintage decyne / Jersey Cape Docking Shirt",
    image: "/images/Vintage decyne Jersey Cape Docking Shirt.webp",
    price: 456,
    color: ["Black"],
    categories: ["Shirt", "Lady", "Men"],
    size: ["M"],
    desc: "A combination series of desing fabric and jersey with a mild sheen and strong drape. The left half is a shirt and the right half is a cloak, each made of a different material.",
  },
  {
    id: 10,
    name: "40/2 Jersey China Big Hoodie pullover",
    image: "/images/402 Jersey China Big Hoodie pullover.webp",
    price: 180,
    color: ["White"],
    categories: ["Hoodie", "Lady", "Men"],
    size: ["M"],
    desc: "A pullover hoodie that uses Chinese knot buttons instead of zippers or buttons.It has a big silhouette with its tail longer than its front. It comes with slash pockets.",
  },
];
